name: Actions 😎

on:
  pull_request: {}
  push: { branches: [ci, master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.6
        with:
          unityVersion: 2019.3.0f6

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.12
        with:
          unityVersion: 2019.3.0f6
          targetPlatform: WebGL 

      # Output 
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build